export interface CityOption {
  label: string;
  value: string;
  state: string;
}

export const TOP_MARKETS: CityOption[] = [
  { label: "Cleveland", value: "cleveland-oh", state: "OH" },
  { label: "Memphis", value: "memphis-tn", state: "TN" },
  { label: "Detroit", value: "detroit-mi", state: "MI" },
  { label: "Indianapolis", value: "indianapolis-in", state: "IN" },
  { label: "Columbus", value: "columbus-oh", state: "OH" },
  { label: "Birmingham", value: "birmingham-al", state: "AL" },
  { label: "St. Louis", value: "st-louis-mo", state: "MO" },
  { label: "Kansas City", value: "kansas-city-mo", state: "MO" },
  { label: "Milwaukee", value: "milwaukee-wi", state: "WI" },
  { label: "Baltimore", value: "baltimore-md", state: "MD" },
  { label: "Philadelphia", value: "philadelphia-pa", state: "PA" },
  { label: "Jacksonville", value: "jacksonville-fl", state: "FL" },
  { label: "San Antonio", value: "san-antonio-tx", state: "TX" },
  { label: "Houston", value: "houston-tx", state: "TX" },
  { label: "Dallas", value: "dallas-tx", state: "TX" },
  { label: "Fort Worth", value: "fort-worth-tx", state: "TX" },
  { label: "Oklahoma City", value: "oklahoma-city-ok", state: "OK" },
  { label: "Tulsa", value: "tulsa-ok", state: "OK" },
  { label: "Little Rock", value: "little-rock-ar", state: "AR" },
  { label: "Louisville", value: "louisville-ky", state: "KY" },
  { label: "Cincinnati", value: "cincinnati-oh", state: "OH" },
  { label: "Dayton", value: "dayton-oh", state: "OH" },
  { label: "Akron", value: "akron-oh", state: "OH" },
  { label: "Toledo", value: "toledo-oh", state: "OH" },
  { label: "Pittsburgh", value: "pittsburgh-pa", state: "PA" },
  { label: "Buffalo", value: "buffalo-ny", state: "NY" },
  { label: "Rochester", value: "rochester-ny", state: "NY" },
  { label: "Syracuse", value: "syracuse-ny", state: "NY" },
  { label: "Hartford", value: "hartford-ct", state: "CT" },
  { label: "New Haven", value: "new-haven-ct", state: "CT" },
  { label: "Richmond", value: "richmond-va", state: "VA" },
  { label: "Norfolk", value: "norfolk-va", state: "VA" },
  { label: "Columbia", value: "columbia-sc", state: "SC" },
  { label: "Augusta", value: "augusta-ga", state: "GA" },
  { label: "Savannah", value: "savannah-ga", state: "GA" },
  { label: "Atlanta", value: "atlanta-ga", state: "GA" },
  { label: "Jackson", value: "jackson-ms", state: "MS" },
  { label: "Shreveport", value: "shreveport-la", state: "LA" },
  { label: "Baton Rouge", value: "baton-rouge-la", state: "LA" },
  { label: "New Orleans", value: "new-orleans-la", state: "LA" },
  { label: "Wichita", value: "wichita-ks", state: "KS" },
  { label: "Omaha", value: "omaha-ne", state: "NE" },
  { label: "Des Moines", value: "des-moines-ia", state: "IA" },
  { label: "Minneapolis", value: "minneapolis-mn", state: "MN" },
  { label: "Gary", value: "gary-in", state: "IN" },
  { label: "South Bend", value: "south-bend-in", state: "IN" },
  { label: "Flint", value: "flint-mi", state: "MI" },
  { label: "Lansing", value: "lansing-mi", state: "MI" },
  { label: "Grand Rapids", value: "grand-rapids-mi", state: "MI" },
  { label: "Chattanooga", value: "chattanooga-tn", state: "TN" },
];
